### ISSUE TITLE
No peers

### ISSUE THREAD

**Issue by millette** [karissa/hyperhealth#9]
I'm using dat 13.8.2 and just installed hyperhealth globally.

I've got 2-3 peers on the same archive, but hyperhealth shows 0 peers. Could it be because some dependencies are too old?

**Comment by okdistribute** [comment]
Yes definitely. There is a branch in which we've attempted to update it -- any help welcome

**Comment by millette** [comment]
Won't promise anything, but I'll try and have a look.
